name: Android Build

on:
  workflow_call:
    inputs:
      NVMRC:
        required: true
        type: string


jobs:
  build_example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node ${{ inputs.NVMRC }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NVMRC }}

      - name: Setup JDK zulu 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - run: yarn install --immutable --check-cache
        working-directory: example

      - run: ./gradlew assemble
        working-directory: example/android
